### ISSUE TITLE
Add PHP8 to composer.json

### ISSUE THREAD

**Issue by fermino** [lfkeitel/php-totp#1]
Hi! Would it be possible to add PHP 8 to composer.json and make a new release in packagist?
For what I can see the code should be compatible. 

Thanks!! :)

**Comment by lfkeitel** [comment]
I apologize for the long delay. I didn't get a notification about this issue or your PR. The PR has been merged and Packagist has and updated 1.1.0 which is marked as compatible with PHP 8. Let me know if you run into any issues.
